-- Create watched_episodes table
CREATE TABLE IF NOT EXISTS public.watched_episodes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id text NOT NULL,
    tmdb_id bigint NOT NULL,
    season_number int NOT NULL,
    episode_number int NOT NULL,
    watched_at timestamptz DEFAULT now(),
    CONSTRAINT watched_episodes_unique_idx UNIQUE (
        user_id,
        tmdb_id,
        season_number,
        episode_number
    )
);

-- Enable RLS
ALTER TABLE public.watched_episodes ENABLE ROW LEVEL SECURITY;

-- Create simple policy for all operations (consistent with previous fixes)
-- We trust the client logic for now as auth is handled via Firebase on frontend
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON public.watched_episodes;

CREATE POLICY "Enable all access for authenticated users" ON public.watched_episodes FOR ALL USING (true)
WITH
    CHECK (true);